###
GET http://localhost:8081/api/review/0
###

###
GET http://localhost:8081/api/review
Content-Type: application/json

{
    "lang": "c"
}
###

###
POST http://localhost:8081/api/review
Content-Type: application/json

{
    "data_id": 0,
    "rating_information": 5,
    "rating_relevence": 5,
    "comment": "test",
    "name": "test",
    "organization": "test"
}
###
